TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS = -O1 -g
ASFLAGS = -g

# object files

OBJS= $(STARTUP) main.o f3d_led.o f3d_uart.o stm32f30x_rcc.o stm32f30x_gpio.o stm32f30x_usart.o newlib_stubs.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common
